# Generated by Django 4.2.16 on 2024-12-25 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="GST_number",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_created",
            field=models.DateField(
                blank=True, default=datetime.datetime.today, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_days",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
