# Generated by Django 4.2.16 on 2024-12-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_profile_gst_number_profile_date_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_created",
        ),
        migrations.AddField(
            model_name="profile",
            name="company_details",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="employee_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="profile",
            name="establishment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.AddField(
            model_name="profile",
            name="business_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.business_type",
            ),
        ),
    ]
