# Generated by Django 4.2.16 on 2024-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_business_type_remove_order_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="business_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="business_type",
            field=models.ManyToManyField(blank=True, to="store.business_type"),
        ),
    ]
