# Generated by Django 4.2.5 on 2024-12-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('rainy', 'Rainy')], default='summer', max_length=20),
        ),
    ]
