# Generated by Django 4.2.16 on 2024-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_remove_profile_business_type_profile_business_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company_details",
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
