# Generated by Django 4.2.5 on 2024-12-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('rainy', 'Rainy')], default='none', max_length=10, null=True),
        ),
    ]
