# Generated by Django 4.2.5 on 2025-01-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_festival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='product',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.festival'),
        ),
    ]
