# Generated by Django 4.2.5 on 2025-01-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loc_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/location_images/'),
        ),
    ]
