# Generated by Django 4.2.5 on 2025-01-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_profile_loc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loc_image',
        ),
    ]
