# Generated by Django 4.2.5 on 2025-01-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productattribute'),
        ('store', '0016_category_icon'),
    ]

    operations = [
    ]
