# Generated by Django 4.2.16 on 2025-01-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0019_alter_productattribute_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="store.product",
            ),
        ),
    ]
