# Generated by Django 4.2.16 on 2025-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0021_profile_seller_req_seller_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="want_to_prime",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Seller_request",
        ),
    ]
