# Generated by Django 4.2.16 on 2025-01-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0022_profile_want_to_prime_delete_seller_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
