# Generated by Django 4.2.16 on 2025-01-18 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0023_profile_is_admin"),
        ("store", "0025_product_image_1_product_image_2_product_image_3_and_more"),
    ]

    operations = []
