# Generated by Django 4.2.5 on 2025-01-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(upload_to='upload/images/'),
        ),
    ]
