# Generated by Django 4.2.5 on 2025-01-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city1',
            new_name='city',
        ),
    ]
