# Generated by Django 4.2.5 on 2025-01-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_rename_city1_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, help_text="Comma-separated list of keywords (e.g., 'organic milk, whole milk, dairy milk')", max_length=255, null=True),
        ),
    ]
