# Generated by Django 4.2.5 on 2025-01-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_merge_20250118_1646'),
        ('store', '0031_product_created_at'),
    ]

    operations = [
    ]
